package br.upis.ltpiv.turma352.series_mix.model;
// Generated 23/04/2012 12:19:58 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Serie generated by hbm2java
 */
public class Serie implements java.io.Serializable {

    private Long id;
    private String nome;
    private String sinopse;
    private Date duracao;
    private String situacao;
    private Date lancamento;
    private Date cancelamento;
    private Set temporadas = new HashSet(0);

    public Serie() {
    }

    public Serie(String nome, String sinopse, Date duracao, String situacao, Date lancamento) {
        this.nome = nome;
        this.sinopse = sinopse;
        this.duracao = duracao;
        this.situacao = situacao;
        this.lancamento = lancamento;
    }

    public Serie(String nome, String sinopse, Date duracao, String situacao, Date lancamento, Date cancelamento, Set temporadas) {
        this.nome = nome;
        this.sinopse = sinopse;
        this.duracao = duracao;
        this.situacao = situacao;
        this.lancamento = lancamento;
        this.cancelamento = cancelamento;
        this.temporadas = temporadas;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSinopse() {
        return this.sinopse;
    }

    public void setSinopse(String sinopse) {
        this.sinopse = sinopse;
    }

    public Date getDuracao() {
        return this.duracao;
    }

    public void setDuracao(Date duracao) {
        this.duracao = duracao;
    }

    public String getSituacao() {
        return this.situacao;
    }

    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    public Date getLancamento() {
        return this.lancamento;
    }

    public void setLancamento(Date lancamento) {
        this.lancamento = lancamento;
    }

    public Date getCancelamento() {
        return this.cancelamento;
    }

    public void setCancelamento(Date cancelamento) {
        this.cancelamento = cancelamento;
    }

    public Set getTemporadas() {
        return this.temporadas;
    }

    public void setTemporadas(Set temporadas) {
        this.temporadas = temporadas;
    }
}