package br.upis.ltpiv.turma352.series_mix.model;
// Generated 23/04/2012 12:19:58 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Temporada generated by hbm2java
 */
public class Temporada implements java.io.Serializable {

    private Long id;
    private Serie serie;
    private int numero;
    private byte[] capa;
    private String trailer;
    private boolean final_;
    private Set comentarios = new HashSet(0);
    private Set episodios = new HashSet(0);

    public Temporada() {
    }

    public Temporada(Serie serie, int numero, boolean final_) {
        this.serie = serie;
        this.numero = numero;
        this.final_ = final_;
    }

    public Temporada(Serie serie, int numero, byte[] capa, String trailer, boolean final_, Set comentarios, Set episodios) {
        this.serie = serie;
        this.numero = numero;
        this.capa = capa;
        this.trailer = trailer;
        this.final_ = final_;
        this.comentarios = comentarios;
        this.episodios = episodios;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Serie getSerie() {
        return this.serie;
    }

    public void setSerie(Serie serie) {
        this.serie = serie;
    }

    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public byte[] getCapa() {
        return this.capa;
    }

    public void setCapa(byte[] capa) {
        this.capa = capa;
    }

    public String getTrailer() {
        return this.trailer;
    }

    public void setTrailer(String trailer) {
        this.trailer = trailer;
    }

    public boolean isFinal_() {
        return this.final_;
    }

    public void setFinal_(boolean final_) {
        this.final_ = final_;
    }

    public Set getComentarios() {
        return this.comentarios;
    }

    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }

    public Set getEpisodios() {
        return this.episodios;
    }

    public void setEpisodios(Set episodios) {
        this.episodios = episodios;
    }
}