package br.upis.ltpiv.turma352.series_mix.model;
// Generated 23/04/2012 12:19:58 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Long id;
    private String nome;
    private String email;
    private String senha;
    private int nivel;
    private Date cadastro;
    private Set comentarios = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nome, String email, String senha, int nivel, Date cadastro) {
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.nivel = nivel;
        this.cadastro = cadastro;
    }

    public Usuario(String nome, String email, String senha, int nivel, Date cadastro, Set comentarios) {
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.nivel = nivel;
        this.cadastro = cadastro;
        this.comentarios = comentarios;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public int getNivel() {
        return this.nivel;
    }

    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    public Date getCadastro() {
        return this.cadastro;
    }

    public void setCadastro(Date cadastro) {
        this.cadastro = cadastro;
    }

    public Set getComentarios() {
        return this.comentarios;
    }

    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
}