package br.upis.ltpiv.turma352.series_mix.model;
// Generated 23/04/2012 12:19:58 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Comentario generated by hbm2java
 */
public class Comentario implements java.io.Serializable {

    private Long id;
    private Temporada temporada;
    private Episodio episodio;
    private Usuario usuario;
    private String mensagem;
    private Date postagem;

    public Comentario() {
    }

    public Comentario(Temporada temporada, Episodio episodio, Usuario usuario, String mensagem, Date postagem) {
        this.temporada = temporada;
        this.episodio = episodio;
        this.usuario = usuario;
        this.mensagem = mensagem;
        this.postagem = postagem;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Temporada getTemporada() {
        return this.temporada;
    }

    public void setTemporada(Temporada temporada) {
        this.temporada = temporada;
    }

    public Episodio getEpisodio() {
        return this.episodio;
    }

    public void setEpisodio(Episodio episodio) {
        this.episodio = episodio;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getMensagem() {
        return this.mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    public Date getPostagem() {
        return this.postagem;
    }

    public void setPostagem(Date postagem) {
        this.postagem = postagem;
    }
}