package br.upis.ltpiv.turma352.series_mix.model;
// Generated 23/04/2012 12:19:58 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Episodio generated by hbm2java
 */
public class Episodio implements java.io.Serializable {

    private Long id;
    private Temporada temporada;
    private int numero;
    private String nome;
    private Date lancamento;
    private Date postagem;
    private Long visita;
    private Set comentarios = new HashSet(0);
    private Set servidors = new HashSet(0);

    public Episodio() {
    }

    public Episodio(Temporada temporada, int numero, String nome, Date lancamento, Date postagem) {
        this.temporada = temporada;
        this.numero = numero;
        this.nome = nome;
        this.lancamento = lancamento;
        this.postagem = postagem;
    }

    public Episodio(Temporada temporada, int numero, String nome, Date lancamento, Date postagem, Long visita, Set comentarios, Set servidors) {
        this.temporada = temporada;
        this.numero = numero;
        this.nome = nome;
        this.lancamento = lancamento;
        this.postagem = postagem;
        this.visita = visita;
        this.comentarios = comentarios;
        this.servidors = servidors;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Temporada getTemporada() {
        return this.temporada;
    }

    public void setTemporada(Temporada temporada) {
        this.temporada = temporada;
    }

    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Date getLancamento() {
        return this.lancamento;
    }

    public void setLancamento(Date lancamento) {
        this.lancamento = lancamento;
    }

    public Date getPostagem() {
        return this.postagem;
    }

    public void setPostagem(Date postagem) {
        this.postagem = postagem;
    }

    public Long getVisita() {
        return this.visita;
    }

    public void setVisita(Long visita) {
        this.visita = visita;
    }

    public Set getComentarios() {
        return this.comentarios;
    }

    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }

    public Set getServidors() {
        return this.servidors;
    }

    public void setServidors(Set servidors) {
        this.servidors = servidors;
    }
}