package br.upis.ltpiv.turma352.series_mix.model;
// Generated 23/04/2012 12:19:58 by Hibernate Tools 3.2.1.GA

/**
 * Servidor generated by hbm2java
 */
public class Servidor implements java.io.Serializable {

    private Long id;
    private Episodio episodio;
    private String nome;
    private String endereco;
    private String situacao;

    public Servidor() {
    }

    public Servidor(Episodio episodio, String nome, String endereco, String situacao) {
        this.episodio = episodio;
        this.nome = nome;
        this.endereco = endereco;
        this.situacao = situacao;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Episodio getEpisodio() {
        return this.episodio;
    }

    public void setEpisodio(Episodio episodio) {
        this.episodio = episodio;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEndereco() {
        return this.endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public String getSituacao() {
        return this.situacao;
    }

    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
}